version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile.webapp
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
