# Dockerfile.webapp
FROM node AS build
WORKDIR /app
COPY . .
RUN npm install @quasar/cli
RUN npm install
RUN npx quasar build

FROM nginx:alpine AS final
COPY --from=build /app/dist/spa /usr/share/nginx/html
